name: Create Trello Board

# Controls when the action will run: whenever there's a push to the main branch
on:
  workflow_dispatch:  # Trigger the workflow manually
    inputs:
      board_name:
        description: 'Board name'
        required: true
        type: string

# Define the jobs that will be run
jobs:
  run-script:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment
    environment: CI
    env:
      TRELLO_KEY: ${{ secrets.TRELLO_KEY }}
      TRELLO_TOKEN: ${{ secrets.TRELLO_TOKEN }}
      TRELLO_MEMBERS: ${{ secrets.TRELLO_MEMBERS }}

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3  # Checkout the current repo

      # Step 2: Set up Python environment
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Specify Python version

      # Step 3: Install dependencies (if required)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Step 4: Run your Python script
      - name: Run script
        run: |
          python trello.py --create --board_name "${{ github.event.inputs.board_name }}"
